### ISSUE TITLE
Is there another way to do this? I don’t have a Windows machine!

### ISSUE THREAD

**Issue by BobWs** [PolicyPuma4/surfshark-wireguard-tunnel-generator#1]
Hi,
Is there another way to do this, because I don’t have a Windows machine.
TIA

**Comment by PolicyPuma** [comment]
> Hi, Is there another way to do this, because I don’t have a Windows machine. TIA

So far I've not documented anything because it's a relatively basic app that doesn't require any command line arguments, most if not all Windows users know how to run executables.

I haven't made a Linux binary... yet. It should be possible if Surfshark has a Linux client, I'll keep you updated if I get around to it.

**Comment by PolicyPuma** [comment]
Addressed in [v2.4](https://github.com/PolicyPuma4/surfshark-wireguard-tunnel-generator/releases/tag/v2.4).
